// Mock data for Lovable preview environment
import type {
  Client,
  Contract,
  ContractUpsell,
  Lead,
  SalesProcess,
  Stage,
  Comment,
  CommentEntityType,
} from "./api";
import { SALES_STAGE } from "@/constants/stages";

export const isLovablePreview = () => {
  if (typeof window === "undefined") return false;
  const host = window.location.hostname;
  return (
    host.includes("lovableproject.com") ||
    host.includes("lovable.app") ||
    host.includes("webcontainer")
  );
};

export const mockClients: Client[] = [
  {
    id: 1,
    name: "Max Mustermann",
    email: "max@example.com",
    phone: "+49 123 456789",
    source: "paid",
    source_stage_name: "Workshop Q1",
    status: "active",
  },
  {
    id: 2,
    name: "Anna Schmidt",
    email: "anna@example.com",
    phone: "+49 234 567890",
    source: "organic",
    source_stage_name: null,
    status: "active",
  },
  {
    id: 3,
    name: "Peter Weber",
    email: "peter@example.com",
    phone: "+49 345 678901",
    source: "paid",
    source_stage_name: "Workshop Q2",
    status: "completed",
    completed_at: "2024-11-15",
  },
  {
    id: 4,
    name: "Julia Fischer",
    email: "julia@example.com",
    phone: "+49 456 789012",
    source: "organic",
    source_stage_name: null,
    status: "active",
  },
  {
    id: 5,
    name: "Thomas Müller",
    email: "thomas@example.com",
    phone: "+49 567 890123",
    source: "paid",
    source_stage_name: "Workshop Q1",
    status: "active",
  },
];

export const mockContracts: Contract[] = [
  {
    id: 1,
    client_id: 1,
    client_name: "Max Mustermann",
    sales_process_id: 1,
    start_date: "2024-07-01",
    end_date_computed: "2025-06-30",
    duration_months: 12,
    revenue_total: 12000,
    payment_frequency: "monthly",
    monthly_amount: 1000,
    paid_months: 12,
    paid_amount_total: 12000,
    next_due_date: null,
  },
  {
    id: 2,
    client_id: 2,
    client_name: "Anna Schmidt",
    sales_process_id: 2,
    start_date: "2024-09-01",
    end_date_computed: "2025-02-28",
    duration_months: 6,
    revenue_total: 4500,
    payment_frequency: "monthly",
    monthly_amount: 750,
    paid_months: 6,
    paid_amount_total: 4500,
    next_due_date: null,
  },
  {
    id: 3,
    client_id: 3,
    client_name: "Peter Weber",
    sales_process_id: 3,
    start_date: "2024-10-01",
    end_date_computed: "2025-09-30",
    duration_months: 12,
    revenue_total: 9600,
    payment_frequency: "quarterly",
    monthly_amount: 800,
    paid_months: 9,
    paid_amount_total: 7200,
    next_due_date: "2025-07-01",
  },
  {
    id: 4,
    client_id: 5,
    client_name: "Thomas Müller",
    sales_process_id: 5,
    start_date: "2025-01-01",
    end_date_computed: "2025-06-30",
    duration_months: 6,
    revenue_total: 6000,
    payment_frequency: "monthly",
    monthly_amount: 1000,
    paid_months: 0,
    paid_amount_total: 0,
    next_due_date: "2025-01-01",
  },
];

export const mockSalesProcesses: SalesProcess[] = [
  {
    id: 1,
    client_id: 1,
    client_name: "Max Mustermann",
    client_email: "max@example.com",
    client_phone: "+49 123 456789",
    client_source: "paid",
    stage: "closed",
    follow_up_date: "2025-01-10",
    follow_up_result: true,
    closed: true,
    revenue: 12000,
    stage_id: 1,
  },
  {
    id: 2,
    client_id: 2,
    client_name: "Anna Schmidt",
    client_email: "anna@example.com",
    client_phone: "+49 234 567890",
    client_source: "organic",
    stage: "closed",
    follow_up_date: "2025-02-05",
    follow_up_result: true,
    closed: true,
    revenue: 4500,
    stage_id: null,
  },
  {
    id: 3,
    client_id: 3,
    client_name: "Peter Weber",
    client_email: "peter@example.com",
    client_phone: "+49 345 678901",
    client_source: "paid",
    stage: "closed",
    follow_up_date: "2025-02-25",
    follow_up_result: true,
    closed: true,
    revenue: 9600,
    stage_id: 2,
  },
  {
    id: 4,
    client_id: 4,
    client_name: "Julia Fischer",
    client_email: "julia@example.com",
    client_phone: "+49 456 789012",
    client_source: "organic",
    stage: "follow_up",
    follow_up_date: "2025-12-20",
    follow_up_result: null,
    closed: false,
    revenue: null,
    stage_id: null,
  },
  {
    id: 5,
    client_id: 5,
    client_name: "Thomas Müller",
    client_email: "thomas@example.com",
    client_phone: "+49 567 890123",
    client_source: "paid",
    stage: "closed",
    follow_up_date: "2025-04-10",
    follow_up_result: true,
    closed: true,
    revenue: 6000,
    stage_id: 1,
  },
  {
    id: 6,
    client_id: 6,
    client_name: "Sarah Braun",
    client_email: "sarah@example.com",
    client_phone: "+49 678 901234",
    client_source: "paid",
    stage: "lost",
    follow_up_date: "2025-03-15",
    follow_up_result: true,
    closed: false,
    revenue: null,
    stage_id: 3,
  },
  {
    id: 7,
    client_id: 6,
    client_name: "Lisa Wagner",
    client_email: "lisa@example.com",
    client_phone: "+49 789 012345",
    client_source: "organic",
    stage: "closed",
    follow_up_date: "2025-04-28",
    follow_up_result: true,
    closed: true,
    revenue: 5400,
    stage_id: null,
  },
  {
    id: 8,
    client_id: 7,
    client_name: "Klaus Bauer",
    client_email: "klaus@example.com",
    client_phone: "+49 890 123456",
    client_source: "paid",
    stage: "closed",
    follow_up_date: "2025-06-15",
    follow_up_result: true,
    closed: true,
    revenue: 7200,
    stage_id: 2,
  },
  {
    id: 9,
    client_id: 8,
    client_name: "Maria Hoffmann",
    client_email: "maria@example.com",
    client_phone: "+49 901 234567",
    client_source: "organic",
    stage: "closed",
    follow_up_date: "2025-07-05",
    follow_up_result: true,
    closed: true,
    revenue: 4800,
    stage_id: null,
  },
  {
    id: 10,
    client_id: 9,
    client_name: "Stefan Klein",
    client_email: "stefan@example.com",
    client_phone: "+49 012 345678",
    client_source: "paid",
    stage: "closed",
    follow_up_date: "2025-07-28",
    follow_up_result: true,
    closed: true,
    revenue: 8400,
    stage_id: 3,
  },
  {
    id: 11,
    client_id: 10,
    client_name: "Sabine Wolf",
    client_email: "sabine@example.com",
    client_phone: "+49 111 222333",
    client_source: "organic",
    stage: "closed",
    follow_up_date: "2025-09-10",
    follow_up_result: true,
    closed: true,
    revenue: 6600,
    stage_id: null,
  },
  {
    id: 12,
    client_id: 11,
    client_name: "Michael Schäfer",
    client_email: "michael@example.com",
    client_phone: "+49 222 333444",
    client_source: "paid",
    stage: "closed",
    follow_up_date: "2025-09-25",
    follow_up_result: true,
    closed: true,
    revenue: 5100,
    stage_id: 1,
  },
  {
    id: 13,
    client_id: 12,
    client_name: "Nicole Braun",
    client_email: "nicole@example.com",
    client_phone: "+49 333 444555",
    client_source: "organic",
    stage: "closed",
    follow_up_date: "2025-11-05",
    follow_up_result: true,
    closed: true,
    revenue: 7800,
    stage_id: null,
  },
  {
    id: 14,
    client_id: 13,
    client_name: "Andreas Richter",
    client_email: "andreas@example.com",
    client_phone: "+49 444 555666",
    client_source: "paid",
    stage: "closed",
    follow_up_date: "2025-11-28",
    follow_up_result: true,
    closed: true,
    revenue: 9000,
    stage_id: 2,
  },
  {
    id: 15,
    client_id: 14,
    client_name: "Petra Lange",
    client_email: "petra@example.com",
    client_phone: "+49 555 666777",
    client_source: "organic",
    stage: "lost",
    follow_up_date: "2025-08-20",
    follow_up_result: true,
    closed: false,
    revenue: null,
    stage_id: null,
  },
  {
    id: 16,
    client_id: 15,
    client_name: "Florian Meier",
    client_email: "florian@example.com",
    client_phone: "+49 666 777888",
    client_source: "organic",
    stage: "erstgespraech",
    follow_up_date: "2026-03-05",
    follow_up_result: null,
    closed: false,
    revenue: null,
    stage_id: null,
  },
  {
    id: 17,
    client_id: 16,
    client_name: "Claudia Neumann",
    client_email: "claudia@example.com",
    client_phone: "+49 777 888999",
    client_source: "paid",
    stage: "erstgespraech",
    follow_up_date: "2026-02-25",
    follow_up_result: null,
    closed: false,
    revenue: null,
    stage_id: 1,
  },
];

export const mockStages: Stage[] = [
  {
    id: 1,
    name: "Workshop Q1 2024",
    date: "2024-03-15",
    ad_budget: 2500,
    registrations: 45,
    participants: 32,
  },
  {
    id: 2,
    name: "Workshop Q2 2024",
    date: "2024-06-20",
    ad_budget: 3000,
    registrations: 52,
    participants: 38,
  },
  {
    id: 3,
    name: "Workshop Q3 2024",
    date: "2024-09-18",
    ad_budget: 2800,
    registrations: 48,
    participants: 35,
  },
  {
    id: 4,
    name: "Workshop Q4 2024",
    date: "2024-12-12",
    ad_budget: 3200,
    registrations: 55,
    participants: 40,
  },
  {
    id: 5,
    name: "Workshop Q1 2025",
    date: "2025-03-20",
    ad_budget: 3500,
    registrations: 30,
    participants: null,
  },
];

export const mockLeads: Lead[] = [
  {
    id: 1,
    name: "Peter Beispiel",
    email: "peter@lead.de",
    phone: "555987654",
    source: "organic",
    source_stage_id: null,
    source_stage_name: null,
    converted: false,
    converted_at: null,
    converted_client_id: null,
    created_at: "2024-12-01T10:00:00Z",
  },
  {
    id: 2,
    name: "Laura Beispiel",
    email: "laura@example.com",
    phone: "444333333",
    source: "paid",
    source_stage_id: 1,
    source_stage_name: "Workshop Q1 2024",
    converted: false,
    converted_at: null,
    converted_client_id: null,
    created_at: "2024-12-05T14:30:00Z",
  },
  {
    id: 3,
    name: "Test Lead",
    email: "test@example.com",
    phone: null,
    source: "organic",
    source_stage_id: null,
    source_stage_name: null,
    converted: false,
    converted_at: null,
    converted_client_id: null,
    created_at: "2024-12-10T09:15:00Z",
  },
  {
    id: 4,
    name: "Converted Lead",
    email: "conv@example.com",
    phone: "111222333",
    source: "organic",
    source_stage_id: null,
    source_stage_name: null,
    converted: true,
    converted_at: "2024-12-15T11:00:00Z",
    converted_client_id: 1,
    created_at: "2024-11-20T08:00:00Z",
  },
  {
    id: 5,
    name: "Sandra Neumann",
    email: "sandra@neumann.de",
    phone: "0176123456",
    source: "paid",
    source_stage_id: 2,
    source_stage_name: "Workshop Q2 2024",
    converted: false,
    converted_at: null,
    converted_client_id: null,
    created_at: "2024-12-18T16:45:00Z",
  },
];

export const mockUpsells: ContractUpsell[] = [
  {
    id: 1,
    sales_process_id: 3,
    client_id: 3,
    upsell_date: "2024-12-01",
    upsell_result: "verlaengerung",
    upsell_revenue: 6000,
    previous_contract_id: 3,
    new_contract_id: 10,
    created_at: "2024-12-01T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z",
    contract_start_date: "2024-12-01",
    contract_duration_months: 6,
    contract_frequency: "monthly",
  },
  {
    id: 2,
    sales_process_id: 5,
    client_id: 5,
    upsell_date: "2024-11-15",
    upsell_result: "keine_verlaengerung",
    upsell_revenue: null,
    previous_contract_id: 5,
    new_contract_id: null,
    created_at: "2024-11-15T09:30:00Z",
    updated_at: "2024-11-15T09:30:00Z",
    contract_start_date: null,
    contract_duration_months: null,
    contract_frequency: null,
  },
];

export const mockUpsellAnalytics = {
  verlangerung_count: 1,
  keine_verlaengerung_count: 1,
  scheduled_count: 0,
  verlangerungsquote: 50,
  umsatz_sum: 6000,
};

// Mock cashflow forecast data - aligned with contracts above
// Max: 1000/mo (ended), Anna: 750/mo (ended), Peter: 800/mo (until Sep 2025), Thomas: 1000/mo (until Jun 2025)
export const mockCashflowForecast = [
  { month: "2025-01", confirmed: 2800, potential: 0 }, // Peter 800 + Thomas 1000 + Max 1000 (last month)
  { month: "2025-02", confirmed: 1800, potential: 0 }, // Peter 800 + Thomas 1000
  { month: "2025-03", confirmed: 1800, potential: 0 },
  { month: "2025-04", confirmed: 1800, potential: 0 },
  { month: "2025-05", confirmed: 1800, potential: 0 },
  { month: "2025-06", confirmed: 1800, potential: 0 }, // Thomas ends
  { month: "2025-07", confirmed: 800, potential: 0 }, // Only Peter
  { month: "2025-08", confirmed: 800, potential: 0 },
  { month: "2025-09", confirmed: 800, potential: 0 }, // Peter ends
  { month: "2025-10", confirmed: 0, potential: 0 },
  { month: "2025-11", confirmed: 0, potential: 0 },
  { month: "2025-12", confirmed: 0, potential: 0 },
];

// Mock comments data
export const mockComments: Comment[] = [
  {
    id: 1,
    entity_type: "client",
    entity_id: 1,
    body: "Sehr engagierter Kunde, hat großes Interesse an unserem Coaching-Programm gezeigt.",
    created_at: "2025-01-10T09:30:00Z",
  },
  {
    id: 2,
    entity_type: "client",
    entity_id: 1,
    body: "Telefongespräch geführt - möchte in Q2 erweitern.",
    created_at: "2025-01-15T14:20:00Z",
  },
  {
    id: 3,
    entity_type: "client",
    entity_id: 2,
    body: "Erste Beratung war sehr positiv. Follow-up nächste Woche geplant.",
    created_at: "2025-01-12T11:00:00Z",
  },
  {
    id: 4,
    entity_type: "contract",
    entity_id: 1,
    body: "Vertrag wurde pünktlich unterzeichnet. Alle Unterlagen vollständig.",
    created_at: "2024-07-01T10:00:00Z",
  },
  {
    id: 5,
    entity_type: "contract",
    entity_id: 1,
    body: "Kunde ist zufrieden mit dem Fortschritt. Verlängerung wahrscheinlich.",
    created_at: "2024-12-15T16:30:00Z",
  },
  {
    id: 6,
    entity_type: "contract",
    entity_id: 3,
    body: "Zahlungserinnerung wurde versendet.",
    created_at: "2025-01-05T09:00:00Z",
  },
  {
    id: 7,
    entity_type: "salesprocess",
    entity_id: 1,
    body: "Erstkontakt per E-Mail. Interesse an Premium-Paket.",
    created_at: "2024-06-15T08:45:00Z",
  },
  {
    id: 8,
    entity_type: "salesprocess",
    entity_id: 1,
    body: "Abschluss erfolgreich! Kunde hat 12-Monats-Vertrag gewählt.",
    created_at: "2024-07-01T11:30:00Z",
  },
  {
    id: 9,
    entity_type: "salesprocess",
    entity_id: 4,
    body: "Follow-up Call angesetzt für nächste Woche.",
    created_at: "2025-01-18T15:00:00Z",
  },
  {
    id: 10,
    entity_type: "salesprocess",
    entity_id: 3,
    body: "Angebot wurde versendet. Wartet auf Rückmeldung.",
    created_at: "2024-09-20T10:15:00Z",
  },
];

// Helper to get mock comments for a specific entity
export const getMockCommentsForEntity = (
  entityType: CommentEntityType,
  entityId: number,
): Comment[] => {
  return mockComments.filter(
    (c) => c.entity_type === entityType && c.entity_id === entityId,
  );
};
