# .github/workflows/deploy.yml
name: Deploy React to GH Pages
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm ci
      - run: npm run build
        env:
          VITE_API_BASE: https://api.yourapp.com # prod API URL
          VITE_BASE_PATH: /sales-assistant-react/ # or "/repo/" for project pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
