# .github/workflows/pr-preview.yml
name: PR Preview (GitHub Pages)

on:
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm ci

      - name: Build PR Preview
        env:
          VITE_BASE_PATH: /annalanah-sales-assistant/preview/pr-${{ github.event.number }}/
          VITE_API_BASE: https://api-dev-yourapp.onrender.com # <-- your backend dev API
          NODE_ENV: production
        run: |
          npm run build
          mv dist preview
          # SPA fallback for this preview path
          mkdir -p preview
          cat > preview/404.html <<EOF
          <!DOCTYPE html>
          <html><head>
            <meta charset="utf-8" />
            <meta http-equiv="refresh" content="0; url=/annalanah-sales-assistant/preview/pr-${{ github.event.number }}/" />
            <script>location.replace("/annalanah-sales-assistant/preview/pr-${{ github.event.number }}/");</script>
          </head><body></body></html>
          EOF

      - name: Publish PR Preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./preview
          destination_dir: preview/pr-${{ github.event.number }}
          keep_files: true

      - name: Comment PR with preview URL
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            🚀 Preview ready:
            https://vr33ni-dev.github.io/annalanah-sales-assistant/preview/pr-${{ github.event.number }}/
